##
# ##
# Project Title
#
# @file
# @version 0.1
build:
	cd build && rm -rf * && cmake .. && cmake --build .


run:
	LD_LIBRARY_PATH=/usr/local/lib/ ./build/osrm-example /tmp/germany-mld/germany-latest.osrm latlon.csv


# end
